spring:
  application:
    name: template-java-app
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

server:
  servlet:
    contextPath: /api

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      profile-name: antigone-dev-tf

parameterstore:
  param-prefix: /template-java-app/app

test.property: This is a default yaml value
